import type { Metadata } from 'next'
import { inter } from '@/assets/styles/fonts'
import '@/assets/styles/globals.css'

export const metadata: Metadata = {
    title: {
        default: 'Smart Real',
        template: '%s | Smart Real Booking'
    },
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={`${inter.className} antialiased`}>
                {children}
            </body>
        </html>
    )
}
